pipeline:
  setup-image-tag:
    environment:
    - DOCKER_REPO=245542037479.dkr.ecr.eu-west-2.amazonaws.com/devops/sentry-new-relic-metrics
    - PROTECTED_FILES_LOCATION=/public/protected-files
    - PUBLIC_FOLDER=/public
    image: croudtech/drone-pipeline-setup:latest
    privileged: true
    pull: true
    when:
      event: tag
      status: success
      ref: refs/tags/docker*
  publish-ecr:
    image: croudtech/drone-docker-ecr:latest
    privileged: true
    pull: true
    region: eu-west-2
    registry: 245542037479.dkr.ecr.eu-west-2.amazonaws.com
    repo: 245542037479.dkr.ecr.eu-west-2.amazonaws.com/devops/sentry-new-relic-metrics
    skip_untagged: true
    when:
      event: tag
      status: success
      ref: refs/tags/docker*
  build:
    image: node
    when:
      event: tag
      status: success
      ref: refs/tags/lambda*
    commands:
      - apt-get update && apt-get install zip
      - cd src
      - yarn
      - zip -r -9 sentry-new-relic-metrics-${DRONE_TAG}.zip *
      - mv sentry-new-relic-metrics-${DRONE_TAG}.zip ../
  s3-publish:
    image: plugins/s3
    when:
      event: tag
      status: success
      ref: refs/tags/lambda*
    acl: private
    region: eu-west-2
    bucket: croudtech-devops-serverless-functions
    target: monitoring
    source: sentry-new-relic-metrics-${DRONE_TAG}.zip
  deploy-lambda:
    when:
      event: deployment
      environment: lambda
      ref: refs/tags/lambda*
    image: omerxx/drone-lambda-plugin
    pull: true
    function_name: sentry-new-relic-metrics
    s3_bucket: croudtech-devops-serverless-functions
    file_name: monitoring/sentry-new-relic-metrics-${DRONE_TAG}.zip
  